language: php

php:
  - 5.6
  - 5.5
  - 7.0

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
